export const GENRES = [
    "Fiction",
    "Sci-Fi",
    "Historical Fiction",
    "Horror",
    "Fantasy",
    "Adventure",
    "Romance",
    "Contemporary Fiction",
    "Literary Fiction",
    "Poetry",
    "Dystopian",
    "Mystery",
    "Comedy",
    "Satire",
    "Graphic Novel",
    "Thriller",
    "Supernatural",
    "Paranormal",
    "Coming-of-Age",
    "Young Adult",
    "Children’s Literature",
    "Autobiographcal Fiction",
    "Essay",
    "Short Stories",
    "Non-Fiction",
    "Travel",
    "Memoir",
    "Cookbook",
    "Art",
    "Photography",
    "Meditation",
    "Self-Help",
    "Development",
    "Motivational",
    "Health",
    "Spirituality",
    "History",
    "Family & Relationships",
    "Textbook",
    "Zine",
]