export const GENRES = [
    "Non-Fiction",
    "Autobiographcal",
    "Travel",
    "Cookbook",
    "Art",
    "Self-Development",
    "Health",
    "Spirituality",
    "History",
    "Fiction",
    "Sci-Fi",
    "Historical Fiction",
    "Horror",
    "Fantasy",
    "Adventure",
    "Romance",
    "Literary Fiction",
    "Poetry",
    "Dystopian",
    "Mystery",
    "Graphic Novel",
    "Thriller",
    "Supernatural",
    "Coming-of-Age",
]